version: '3'

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: 'sportmaster_store'
      POSTGRES_PASSWORD: '123'
      POSTGRES_USER: 'sportmaster_user'
    ports:
      - "5434:5432"

  php-fpm:
    container_name: php-fpm
    build:
      context: ./docker/php-fpm
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./:/var/www
    links:
      - db

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log/nginx
    depends_on:
      - php-fpm
    ports:
      - "81:80"